### ISSUE TITLE
Roadmap to 0.1.0

### ISSUE THREAD

**Issue by mcapuccini** [mcapuccini/terraform-openstack-spark#7]
## Main
- [x] Minimal Spark cluster
- [x] Documentation for the main module
- [x] Distribution 
- [x] GPU support
- [x] Apache Zeppelin

## Errands
- [x] Zeppelin notebook directory should be in the host fs
- [x] Output ssh tunnelling command
- [x] Investigate on https://github.com/aseigneurin/spark-ui-proxy, maybe include if working
